# Generated by Django 5.0.1 on 2024-01-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qavat', models.PositiveSmallIntegerField()),
                ('raqam', models.CharField(max_length=10)),
                ('bino', models.CharField(max_length=10)),
                ('tur', models.CharField(choices=[('Luks', 'Luks'), ('Yarim-luks', 'Yarim-luks'), ('Oddiy', 'Oddiy')], max_length=15)),
                ('sigim', models.PositiveSmallIntegerField()),
                ('bosh_joy_soni', models.PositiveSmallIntegerField()),
                ('narx', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Joylashtirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.CharField(blank=True, max_length=100)),
                ('kelgan_sana', models.DateField()),
                ('ketish_sana', models.DateField(blank=True, null=True)),
                ('yotgan_kun_soni', models.PositiveSmallIntegerField(default=0)),
                ('qarovchi', models.BooleanField(default=False)),
                ('bemor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.bemor')),
                ('xona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xonalar.xona')),
            ],
        ),
    ]
