# Generated by Django 5.0.1 on 2024-01-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('xonalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.PositiveIntegerField()),
                ('tolangan_summa', models.PositiveIntegerField(default=0)),
                ('turi', models.CharField(max_length=50)),
                ('izoh', models.CharField(max_length=100)),
                ('tolandi', models.BooleanField(default=False)),
                ('sana', models.DateField(auto_now_add=True)),
                ('tolangan_sana', models.DateField()),
                ('bemor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.bemor')),
                ('joylashtirish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xonalar.joylashtirish')),
                ('yollanma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.yollanma')),
            ],
        ),
    ]
