# Generated by Django 5.0.1 on 2024-01-19 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolovlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QoshimchaTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('summa', models.PositiveIntegerField()),
                ('izoh', models.TextField(blank=True)),
                ('tolov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolovlar.tolov')),
            ],
        ),
    ]
