# Generated by Django 5.0.1 on 2024-01-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bemor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('manzil', models.CharField(max_length=100)),
                ('joylashgan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Yollanma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('narx', models.PositiveIntegerField()),
                ('qayerga', models.CharField(choices=[('UZI', 'UZI'), ('Shifokor', 'Shifokor'), ('Labaratoriya', 'Labaratoriya')], max_length=30)),
            ],
        ),
    ]
